spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ship_management
    username: root
    password: 123456

  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true # ????????
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ????? SQL ?????????

  mail:
    host: smtp.resend.com
    port: 587               # 修改端口为 587
    username: resend
    password: 
    # protocol: smtp        # 可以注释掉 protocol，让 Spring 自动处理
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    # 587 端口必须开启 STARTTLS
            required: true

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

  servlet:
    multipart:
      max-file-size: 50MB      # 单个文件最大大小 (默认是 1MB)
      max-request-size: 50MB   # 整个请求最大大小 (默认是 10MB)

resend:
  api-key: 
  from-email: 



